pluginManagement {
  includeBuild("build-logic")
  repositories {
    google {
      content {
        includeGroupByRegex("com\\.android.*")
        includeGroupByRegex("com\\.google.*")
        includeGroupByRegex("androidx.*")
      }
    }
    mavenCentral()
    gradlePluginPortal()
  }
}
dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    google()
    mavenCentral()
  }
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "WeatherVibe"
include(":app")
include(":benchmark")
include(":core:ads")
include(":core:ai")
include(":core:analytics")
include(":core:coroutines")
include(":core:network")
include(":core:designsystem")
include(":core:navigation")
include(":core:permissions")
include(":core:sharing")
include(":core:time")
include(":core:tracing")
include(":core:workmanager")
include(":domain:location")
include(":domain:vibe")
include(":domain:weather")
include(":data:location")
include(":data:weather")
include(":feature:home")
include(":feature:search")
include(":feature:splash")
include(":domain:settings")
include(":data:settings")
include(":feature:settings")
include(":domain:widget")
include(":data:widget")
include(":feature:widget")
include(":testing:airquality-fixtures")
include(":testing:alerts-fixtures")
include(":testing:coroutine-rules")
include(":testing:location-fixtures")
include(":testing:settings-fixtures")
include(":testing:time-fixtures")
include(":testing:viberating-fixtures")
include(":testing:weather-fixtures")
include(":testing:widget-fixtures")
include(":domain:alerts")
include(":data:alerts")
include(":domain:airquality")
include(":data:airquality")
include(":notifications")
include(":scheduling")
include(":domain:activityplanner")
include(":feature:activityplanner")
include(":feature:onboarding")
include(":feature:locations")
include(":feature:profile")
include(":data:profile")
include(":domain:profile")
include(":domain:viberating")
include(":data:viberating")
include(":feature:viberating")
include(":domain:appearance")
include(":data:appearance")
include(":domain:remoteconfig")
include(":data:remoteconfig")
include(":domain:ads")
include(":data:ads")
