package com.weather.vibe.feature.home.ui

internal object HomeEmojis {
  fun cloud(): String = "\u2601\uFE0F"
  fun compass(): String = "\uD83E\uDDED"
  fun dewDrop(): String = "\uD83C\uDF3F"
  fun error(): String = "\u26A1"
  fun eye(): String = "\uD83D\uDC41\uFE0F"
  fun gauge(): String = "\uD83D\uDD36"
  fun headphones(): String = "\uD83C\uDFA7"
  fun humidity(): String = "\uD83D\uDCA7"
  fun moon(): String = "\uD83C\uDF19"
  fun mostlySunny(): String = "\uD83C\uDF24\uFE0F"
  fun partlyCloudy(): String = "\u26C5"
  fun precipitation(): String = "\uD83C\uDF02"
  fun rainfall(): String = "\uD83C\uDF27\uFE0F"
  fun snow(): String = "\u2744\uFE0F"
  fun sunny(): String = "\u2600\uFE0F"
  fun sunrise(): String = "\uD83C\uDF05"
  fun sunShower(): String = "\uD83C\uDF26\uFE0F"
  fun sunset(): String = "\uD83C\uDF07"
  fun thunderstorm(): String = "\u26C8\uFE0F"
  fun uvIndex(): String = "\u2600\uFE0F"
  fun wind(): String = "\uD83D\uDCA8"
  fun windGusts(): String = "\uD83C\uDF2C\uFE0F"
  fun windMax(): String = "\uD83D\uDCA5"
  fun vibeRadiant(): String = "\uD83E\uDD29"
  fun vibePleasant(): String = "\uD83D\uDE0A"
  fun vibeOkay(): String = "\uD83D\uDE42"
  fun vibeDreary(): String = "\uD83D\uDE15"
  fun vibeRough(): String = "\uD83D\uDE29"
}
