package com.weather.vibe.feature.home.ui

internal object HomeEmojis {
  fun cloud(): String = "☁️"
  fun compass(): String = "🧭"
  fun dewDrop(): String = "🌿"
  fun error(): String = "⚡"
  fun eye(): String = "👁️"
  fun gauge(): String = "🔶"
  fun headphones(): String = "🎧"
  fun humidity(): String = "💧"
  fun moon(): String = "🌙"
  fun mostlySunny(): String = "🌤️"
  fun partlyCloudy(): String = "⛅"
  fun precipitation(): String = "🌂"
  fun rainfall(): String = "🌧️"
  fun share(): String = "📤"
  fun snow(): String = "❄️"
  fun sunny(): String = "☀️"
  fun sunrise(): String = "🌅"
  fun sunShower(): String = "🌦️"
  fun sunset(): String = "🌇"
  fun thunderstorm(): String = "⛈️"
  fun uvIndex(): String = "☀️"
  fun wind(): String = "💨"
  fun windGusts(): String = "🌬️"
  fun windMax(): String = "💥"
  fun vibeRadiant(): String = "🤩"
  fun vibePleasant(): String = "😊"
  fun vibeOkay(): String = "🙂"
  fun vibeDreary(): String = "😕"
  fun vibeRough(): String = "😩"
}
