package com.weather.vibe

object EnvKeys {

  const val ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY"

  const val KEYSTORE_PATH = "KEYSTORE_PATH"
  const val KEYSTORE_PASSWORD = "KEYSTORE_PASSWORD"
  const val KEY_ALIAS = "KEY_ALIAS"
  const val KEY_PASSWORD = "KEY_PASSWORD"

  const val FIREBASE_SERVICE_ACCOUNT_FILE = "FIREBASE_SERVICE_ACCOUNT_FILE"

  const val VERSION_NAME = "VERSION_NAME"
  const val GITHUB_RUN_NUMBER = "GITHUB_RUN_NUMBER"
}
