package com.weather.vibe.core.designsystem.theme

import androidx.compose.ui.graphics.Color

internal object ColorTokens {

  val AccentLavender = Color(0xFF8B82F6)
  val AccentIndigo = Color(0xFF5B4FE5)
  val BackgroundGradientEnd = Color(0xFF13142C)
  val BackgroundGradientStart = Color(0xFF1B1E3D)
  val DarkError = Color(0xFFCF6679)
  val DarkSuccess = Color(0xFF34D399)
  val GlassBorder = Color(0x33FFFFFF)
  val GlassBorderSubtle = Color(0x14FFFFFF)
  val GlassSurface = Color(0x1AFFFFFF)
  val GlassSurfaceHeavy = Color(0x26FFFFFF)
  val OnAccent = Color(0xFFFFFFFF)
  val PaletteAmber = Color(0xFFFBBF24)
  val PaletteBlue = Color(0xFF38BDF8)
  val SheetSurface = Color(0xFF1B1E3D)
  val DarkCardContainer = Color(0xFF252952)
  val TextPrimary = Color(0xFFF1F5F9)
  val TextSecondary = Color(0xFFA5A6CC)
  val TextTertiary = Color(0xFF6E709D)

  val LightBackground = Color(0xFFF2F1FB)
  val LightCool = Color(0xFF0284C7)
  val LightError = Color(0xFFDC2626)
  val LightOnPrimaryContainer = Color(0xFF1E1B4B)
  val LightOnSurface = Color(0xFF1E1B4B)
  val LightOnSurfaceVariant = Color(0xFF5B5896)
  val LightOutline = Color(0xFFCBD5E1)
  val LightOutlineVariant = Color(0xFFE2E8F0)
  val LightPrimary = Color(0xFF5B4FE5)
  val LightPrimaryContainer = Color(0xFFE0E7FF)
  val LightSuccess = Color(0xFF16A34A)
  val LightSurface = Color(0xFFFFFFFF)
  val LightSurfaceContainer = Color(0xFFF1F5F9)
  val LightTextTertiary = Color(0xFF8A86B5)
  val LightWarm = Color(0xFFD97706)

  val DarkPillCoral = Color(0xFFEF6F6C)
  val DarkPillBlue = Color(0xFF4FC3F7)
  val DarkPillAmber = Color(0xFFFBBF24)
  val DarkPillViolet = Color(0xFFA78BFA)
  val DarkPillTeal = Color(0xFF2DD4BF)
  val DarkPillRose = Color(0xFFF472B6)

  val LightPillCoral = Color(0xFFE11D48)
  val LightPillBlue = Color(0xFF0284C7)
  val LightPillAmber = Color(0xFFD97706)
  val LightPillViolet = Color(0xFF7C3AED)
  val LightPillTeal = Color(0xFF0D9488)
  val LightPillRose = Color(0xFFDB2777)
}
